//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBFluidSwitcherGestureExclusionTrapezoid;

@interface _SBFluidSwitcherGestureExclusionTrapezoidDebugView : UIView
{
    SBFluidSwitcherGestureExclusionTrapezoid *_exclusionTrapezoid;
}

@property(retain, nonatomic) SBFluidSwitcherGestureExclusionTrapezoid *exclusionTrapezoid; // @synthesize exclusionTrapezoid=_exclusionTrapezoid;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

