//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface _SBMainScreenActiveInterfaceOrientationWindowRootViewController : UIViewController
{
    unsigned long long _supportedInterfaceOrientations;
}

@property(nonatomic) unsigned long long supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
- (id)_viewControllerForSupportedInterfaceOrientationsWithDismissCheck:(_Bool)arg1;
- (_Bool)shouldAutorotate;

@end

