//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollViewDelegate.h"

@class UIScrollView;

@protocol BSUIScrollViewDelegate <UIScrollViewDelegate>

@optional
- (void)scrollViewDidEndScrolling:(UIScrollView *)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1 withContext:(CDStruct_3b09cf25)arg2;
- (void)scrollViewWillBeginScrolling:(UIScrollView *)arg1;
@end

