//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCUIModularControlCenterViewControllerDelegate.h"

@class CCUIModularControlCenterCardViewController, UIView;

@protocol CCUIModularControlCenterCardViewControllerDelegate <CCUIModularControlCenterViewControllerDelegate>
- (double)statusTextHeightForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;
- (long long)interfaceOrientationForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;

@optional
- (UIView *)obscuringBackgroundViewForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;
@end

