//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCNotificationRequest.h"

@interface NCNotificationRequest (UserAlert)
+ (id)_notificationSoundFromSound:(id)arg1;
+ (long long)_soundTypeForSBSoundType:(long long)arg1;
+ (id)_notificationOptionsForAlertItem:(id)arg1;
+ (id)_destinations;
+ (id)notificationRequestWithAlertItem:(id)arg1;
@end

