//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBAnalyticsBackendEventHandling.h"

@class NSString;

@interface SBAnalyticsAggdSimpleEventHandler : NSObject <SBAnalyticsBackendEventHandling>
{
    unsigned long long _eventType;
    CDUnknownBlockType _emitBlock;
}

+ (id)setScalarForEvent:(unsigned long long)arg1 aggdKey:(id)arg2 valueBlock:(CDUnknownBlockType)arg3;
+ (id)monotonicallyIncreasingForEvent:(unsigned long long)arg1 aggdKey:(id)arg2;
+ (id)latchForEvent:(unsigned long long)arg1 aggdKey:(id)arg2;
- (void).cxx_destruct;
- (_Bool)handleEvent:(unsigned long long)arg1 withContext:(id)arg2;
- (id)initWithEvent:(unsigned long long)arg1 emitBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

