//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBApplicationLaunchAlertEvaluator.h"

@class NSString, SBAirplaneModeController, SBTelephonyManager, SBWiFiManager;

@interface SBApplicationLaunchAlertEvaluatorForNetworkBasedAlertItems : NSObject <SBApplicationLaunchAlertEvaluator>
{
    SBWiFiManager *_wifiManager;
    SBAirplaneModeController *_airplaneModeController;
    SBTelephonyManager *_telephonyManager;
}

- (void).cxx_destruct;
- (id)_wifiManager;
- (id)_airplaneModeController;
- (id)_telephonyManager;
- (unsigned long long)shouldShowLaunchAlertForApplication:(id)arg1;
- (id)initWithWiFiManager:(id)arg1 airplaneModeController:(id)arg2 telephonyManager:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

