//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBAppSwitcherWallpaperSettings : SBUISettings
{
    long long _deckSwitcherForegroundWallpaperStyle;
    long long _deckSwitcherBackgroundWallpaperStyle;
    double _deckSwitcherForegroundDarkeningFactor;
    double _deckSwitcherBackgroundDarkeningFactor;
    double _deckSwitcherForegroundSaturationDeltaFactor;
    double _deckSwitcherBackgroundSaturationDeltaFactor;
    double _deckSwitcherForegroundBlurRadius;
    double _deckSwitcherBackgroundBlurRadius;
}

+ (id)settingsControllerModule;
@property double deckSwitcherBackgroundBlurRadius; // @synthesize deckSwitcherBackgroundBlurRadius=_deckSwitcherBackgroundBlurRadius;
@property double deckSwitcherForegroundBlurRadius; // @synthesize deckSwitcherForegroundBlurRadius=_deckSwitcherForegroundBlurRadius;
@property double deckSwitcherBackgroundSaturationDeltaFactor; // @synthesize deckSwitcherBackgroundSaturationDeltaFactor=_deckSwitcherBackgroundSaturationDeltaFactor;
@property double deckSwitcherForegroundSaturationDeltaFactor; // @synthesize deckSwitcherForegroundSaturationDeltaFactor=_deckSwitcherForegroundSaturationDeltaFactor;
@property double deckSwitcherBackgroundDarkeningFactor; // @synthesize deckSwitcherBackgroundDarkeningFactor=_deckSwitcherBackgroundDarkeningFactor;
@property double deckSwitcherForegroundDarkeningFactor; // @synthesize deckSwitcherForegroundDarkeningFactor=_deckSwitcherForegroundDarkeningFactor;
@property long long deckSwitcherBackgroundWallpaperStyle; // @synthesize deckSwitcherBackgroundWallpaperStyle=_deckSwitcherBackgroundWallpaperStyle;
@property long long deckSwitcherForegroundWallpaperStyle; // @synthesize deckSwitcherForegroundWallpaperStyle=_deckSwitcherForegroundWallpaperStyle;
- (void)setDefaultValues;

@end

