//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneIdentityProviding.h"

@class FBSSceneIdentity, SBApplication, SBApplicationSceneHandle;

@protocol SBApplicationSceneHandleProviding <SBApplicationSceneIdentityProviding>
- (SBApplicationSceneHandle *)fetchOrCreateApplicationSceneHandleForApplication:(SBApplication *)arg1 withIdentity:(FBSSceneIdentity *)arg2;
@end

