//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBBannerViewCallbackManager, SBUIBannerContext, UIView<SBUIBannerView>;

@interface SBBannerContextView : UIView
{
    SBBannerViewCallbackManager *_callbacks;
    SBBannerViewCallbackManager *_wrapperCallbacks;
    SBUIBannerContext *_bannerContext;
    UIView<SBUIBannerView> *_bannerView;
}

@property(readonly, retain, nonatomic) UIView<SBUIBannerView> *bannerView; // @synthesize bannerView=_bannerView;
@property(readonly, nonatomic) SBUIBannerContext *bannerContext; // @synthesize bannerContext=_bannerContext;
- (void).cxx_destruct;
- (void)noteDidDismissWithReason:(int)arg1;
- (void)noteWillDismissWithReason:(int)arg1;
- (void)noteDidAppear;
- (void)noteWillAppear;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setBannerContext:(id)arg1 withReplaceReason:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

