//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBCarPlayIconImageCache : NSObject
{
}

+ (id)_imageKeyForBundleIdentifier:(id)arg1 inLayout:(id)arg2;
+ (id)_iconImageCache;
+ (id)sharedInstance;
- (void)setIconImage:(id)arg1 forBundleIdentifier:(id)arg2 inLayout:(id)arg3;
- (id)iconImageForBundleIdentifier:(id)arg1 inLayout:(id)arg2;

@end

