//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneEntity.h"

@interface SBCarApplicationSceneEntity : SBApplicationSceneEntity
{
}

- (_Bool)_isValidCarActivationSetting:(unsigned int)arg1;
- (id)carApplicationSceneEntity;
- (_Bool)isCarApplicationSceneEntity;
- (void)applyActivationSettings:(id)arg1;
- (void)setObject:(id)arg1 forActivationSetting:(unsigned int)arg2;
- (void)setFlag:(long long)arg1 forActivationSetting:(unsigned int)arg2;
- (Class)viewControllerClass;
- (id)initWithApplicationSceneEntity:(id)arg1 screenController:(id)arg2;
- (id)initWithApplication:(id)arg1 screenController:(id)arg2;
- (id)initWithApplicationSceneHandle:(id)arg1;

@end

