//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconModel.h"

@class NSArray, NSString;

@interface SBCarPlayIconModel : SBIconModel
{
    _Bool _showsOEMIcon;
    NSArray *_hiddenBundleIdentifiers;
    NSString *_OEMIconLabel;
    struct CGRect _screenBounds;
}

@property(retain, nonatomic) NSString *OEMIconLabel; // @synthesize OEMIconLabel=_OEMIconLabel;
@property(nonatomic) _Bool showsOEMIcon; // @synthesize showsOEMIcon=_showsOEMIcon;
@property(nonatomic) struct CGRect screenBounds; // @synthesize screenBounds=_screenBounds;
@property(retain, nonatomic) NSArray *hiddenBundleIdentifiers; // @synthesize hiddenBundleIdentifiers=_hiddenBundleIdentifiers;
- (void).cxx_destruct;
- (void)_importStateWithoutLayout:(id)arg1;
- (void)persistIconStateWithoutLayout;
- (void)resetCurrentIconState;
- (id)exportStateForCarKit;
- (_Bool)importState:(id)arg1;
- (void)didUnarchiveMetadata:(id)arg1;
- (id)iconModelMetadata;
- (_Bool)isIconVisible:(id)arg1;
@property(readonly, nonatomic) unsigned long long columnCount;
@property(readonly, nonatomic) unsigned long long rowCount;
- (id)initWithStore:(id)arg1 applicationDataSource:(id)arg2;

@end

