//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UNUserNotificationCenterObserver.h"

@class NSString, UNUserNotificationCenter;

@interface SBClockNotificationManager : NSObject <UNUserNotificationCenterObserver>
{
    UNUserNotificationCenter *_userNotificationCenter;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_updateTimerShortcutItems;
- (void)_updateAlarmStatusBarItemForPendingNotificationRequests:(id)arg1;
- (void)userNotificationCenter:(id)arg1 didChangePendingNotificationRequests:(id)arg2;
- (void)userNotificationCenter:(id)arg1 didDeliverNotifications:(id)arg2;
- (void)removePendingNotificationRequestsWithIdentifier:(id)arg1;
- (void)getPendingNotificationRequestsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)addNotificationRequest:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

