//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAWDMetric.h"

@interface SBClawGestureMetric : SBAWDMetric
{
}

- (id)configureWithData:(id)arg1;
- (Class)dataClass;
- (unsigned long long)metricID;
- (void)postWithDataBuilder:(CDUnknownBlockType)arg1;

@end

