//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBToAppsWorkspaceTransaction.h"

@class SBAlertToAppsWorkspaceTransaction, SBDismissOverlaysAnimationController;

@interface SBCoverSheetToAppsWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    SBAlertToAppsWorkspaceTransaction *_alertToAppsTransaction;
    SBDismissOverlaysAnimationController *_dismissOverlaysAnimationController;
    _Bool _preservesBanners;
}

@property(nonatomic) _Bool preservesBanners; // @synthesize preservesBanners=_preservesBanners;
- (void).cxx_destruct;
- (unsigned long long)_dismissOverlaysOptions;
- (void)_dismissOverlaysIfNeeded;
- (void)_coverSheetDidDismiss:(id)arg1;
- (void)activateApplications;
- (void)_begin;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;

@end

