//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIHostStatusBarStyleProvider.h"
#import "CCUIModularControlCenterOverlayViewControllerDelegate.h"
#import "SBBarSwipeAffordanceDelegate.h"
#import "SBBarSwipeAffordanceObserver.h"
#import "SBDashBoardExternalAppearanceProviding.h"
#import "SBDashBoardExternalBehaviorProviding.h"
#import "SBDashBoardExternalPresentationProviding.h"
#import "SBGrabberTongueDelegate.h"
#import "SBIdleTimerProviding.h"
#import "SBReachabilityObserver.h"
#import "UIGestureRecognizerDelegate.h"

@class BSSimpleAssertion, CCUIModularControlCenterOverlayViewController, CCUIStatusBarStyleSnapshot, FBDisplayLayoutElement, FBUIApplicationSceneDeactivationAssertion, NSArray, NSHashTable, NSSet, NSString, SBAppStatusBarSettingsAssertion, SBBarSwipeAffordanceViewController, SBControlCenterSystemAgent, SBControlCenterWindow, SBDashBoardLayoutStrategy, SBGrabberTongue, UIColor, UIPanGestureRecognizer, _UILegibilitySettings;

@interface SBControlCenterController : NSObject <CCUIModularControlCenterOverlayViewControllerDelegate, SBGrabberTongueDelegate, SBDashBoardExternalBehaviorProviding, SBDashBoardExternalPresentationProviding, SBDashBoardExternalAppearanceProviding, UIGestureRecognizerDelegate, SBBarSwipeAffordanceObserver, SBBarSwipeAffordanceDelegate, CCUIHostStatusBarStyleProvider, SBReachabilityObserver, SBIdleTimerProviding>
{
    SBDashBoardLayoutStrategy *_layoutStrategy;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBControlCenterWindow *_window;
    CCUIModularControlCenterOverlayViewController *_viewController;
    SBBarSwipeAffordanceViewController *_homeAffordanceViewController;
    SBControlCenterSystemAgent *_systemAgent;
    BSSimpleAssertion *_hideStatusBarAssertion;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    SBGrabberTongue *_grabberTongue;
    UIPanGestureRecognizer *_statusBarPullGestureRecognizer;
    FBUIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    FBDisplayLayoutElement *_displayLayoutElement;
    NSHashTable *_observers;
    id <BSInvalidatable> _idleTimerDisableAssertion;
}

+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
+ (id)_sharedInstanceCreatingIfNeeded:(_Bool)arg1;
@property(retain, nonatomic) id <BSInvalidatable> idleTimerDisableAssertion; // @synthesize idleTimerDisableAssertion=_idleTimerDisableAssertion;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) FBDisplayLayoutElement *displayLayoutElement; // @synthesize displayLayoutElement=_displayLayoutElement;
@property(retain, nonatomic) FBUIApplicationSceneDeactivationAssertion *resignActiveAssertion; // @synthesize resignActiveAssertion=_resignActiveAssertion;
@property(retain, nonatomic) UIPanGestureRecognizer *statusBarPullGestureRecognizer; // @synthesize statusBarPullGestureRecognizer=_statusBarPullGestureRecognizer;
@property(retain, nonatomic) SBGrabberTongue *grabberTongue; // @synthesize grabberTongue=_grabberTongue;
@property(retain, nonatomic) SBAppStatusBarSettingsAssertion *statusBarAssertion; // @synthesize statusBarAssertion=_statusBarAssertion;
@property(retain, nonatomic) BSSimpleAssertion *hideStatusBarAssertion; // @synthesize hideStatusBarAssertion=_hideStatusBarAssertion;
@property(retain, nonatomic) SBControlCenterSystemAgent *systemAgent; // @synthesize systemAgent=_systemAgent;
@property(retain, nonatomic) SBBarSwipeAffordanceViewController *homeAffordanceViewController; // @synthesize homeAffordanceViewController=_homeAffordanceViewController;
@property(retain, nonatomic) CCUIModularControlCenterOverlayViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) SBControlCenterWindow *window; // @synthesize window=_window;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
@property(retain, nonatomic) SBDashBoardLayoutStrategy *layoutStrategy; // @synthesize layoutStrategy=_layoutStrategy;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CCUIStatusBarStyleSnapshot *hostStatusBarStyle;
- (double)_homeAffordanceAnimationDelay;
- (id)unhideAnimationSettingsForBarSwipeAffordanceView:(id)arg1;
- (id)hideAnimationSettingsForBarSwipeAffordanceView:(id)arg1;
- (void)homeGesturePerformedForBarSwipeAffordanceView:(id)arg1;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, nonatomic) long long backgroundStyle;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (_Bool)_shouldShowGrabberOnFirstSwipe;
- (_Bool)_shouldAllowControlCenterGesture;
- (_Bool)allowShowTransitionSystemGesture;
- (_Bool)allowShowTransition;
- (_Bool)_isLocationXWithinTrailingStatusBarRegion:(double)arg1;
- (struct CGPoint)_presentGestureVelocityInView;
- (struct CGPoint)_presentGestureTranslationInView:(_Bool)arg1;
- (struct CGPoint)_presentGestureLocationInView;
- (void)_uiRelockedNotification:(id)arg1;
- (void)_lockStateChangedNotification:(id)arg1;
- (void)_enumerateObservers:(CDUnknownBlockType)arg1;
- (id)_controlCenterWindow;
- (void)_setStatusBarHidden:(_Bool)arg1;
- (void)_updateWindowVisibility;
- (void)_updateWindowOrientation;
- (void)_didDismiss;
- (void)_didPresent;
- (void)_willPresent;
- (void)_didEndTransition;
- (void)_willBeginTransition;
- (void)didCloseExpandedModuleForControlCenterViewController:(id)arg1;
- (void)willOpenExpandedModuleForControlCenterViewController:(id)arg1;
- (void)controlCenterViewController:(id)arg1 significantPresentationProgressChange:(double)arg2;
- (void)controlCenterViewController:(id)arg1 didChangePresentationState:(unsigned long long)arg2;
- (double)reachabilityOffsetForControlCenterViewController:(id)arg1;
- (void)controlCenterViewController:(id)arg1 wantsHostStatusBarHidden:(_Bool)arg2;
- (id)customGestureRecognizerForGrabberTongue:(id)arg1;
- (void)grabberTongueCanceledPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueEndedPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueUpdatedPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueBeganPulling:(id)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueDidDismiss:(id)arg1;
- (void)grabberTongueWillPresent:(id)arg1;
- (_Bool)grabberTongue:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)grabberTongueHonorsAmbiguousActivationMargin:(id)arg1;
- (_Bool)grabberTongueRequiredOutsideGrabberFreeRegion:(id)arg1;
- (_Bool)grabberTongueRequiredForWholeEdge:(id)arg1;
- (_Bool)grabberTongueOrPullEnabled:(id)arg1;
- (void)_handleStatusBarPullDownGesture:(id)arg1;
- (void)_disableReachability;
- (double)_reachabilityOffsetForLayout;
- (double)_reachabilityOffsetForGestureRecognition;
- (void)handleReachabilityModeDeactivated;
- (void)handleReachabilityModeActivated;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_requireGestureRecognizerToFailForPresentGestureRecognizer:(id)arg1;
- (void)_requirePresentGestureRecognizerToFailForGestureRecognizer:(id)arg1;
- (void)_dismissExpandedModuleWithCompletion:(CDUnknownBlockType)arg1;
- (void)_presentExpandedModuleWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissAnimated:(_Bool)arg1;
- (void)presentAnimated:(_Bool)arg1;
- (_Bool)handleMenuButtonTap;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, nonatomic) unsigned long long presentingEdge;
@property(readonly, nonatomic, getter=isVisible) _Bool visible;
- (_Bool)isPresentedOrDismissing;
@property(readonly, nonatomic, getter=isPresented) _Bool presented;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

