//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SBDashBoardClippingLine : UIView
{
    UIView *_realLine;
}

- (void).cxx_destruct;
@property(nonatomic) double lineAlpha;
- (id)initWithFrame:(struct CGRect)arg1;

@end

