//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBLockScreenActionContext;

@interface SBDashBoardAction : NSObject
{
    long long _type;
    SBLockScreenActionContext *_context;
}

+ (id)actionWithContext:(id)arg1;
+ (id)actionWithType:(long long)arg1;
@property(retain, nonatomic) SBLockScreenActionContext *context; // @synthesize context=_context;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;

@end

