//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewBase.h"

@class SBDashBoardPageControl, SBPagedScrollView, SBShakableView, SBUICallToActionLabel, SBUILegibilityLabel, UIView<SBUILegibility>, _UILegibilitySettings;

@interface SBDashBoardFixedFooterView : SBDashBoardViewBase
{
    _UILegibilitySettings *_legibilitySettings;
    SBShakableView *_callToActionShakeView;
    SBUICallToActionLabel *_callToActionLabel;
    SBUILegibilityLabel *_alternateCallToActionLabel;
    double _alternateCallToActionLabelOffset;
    UIView<SBUILegibility> *_statusTextView;
    SBDashBoardPageControl *_pageControl;
    SBPagedScrollView *_trackingScrollViewForPageControl;
}

@property(nonatomic) __weak SBPagedScrollView *trackingScrollViewForPageControl; // @synthesize trackingScrollViewForPageControl=_trackingScrollViewForPageControl;
@property(readonly, nonatomic) SBDashBoardPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIView<SBUILegibility> *statusTextView; // @synthesize statusTextView=_statusTextView;
@property(nonatomic) double alternateCallToActionLabelOffset; // @synthesize alternateCallToActionLabelOffset=_alternateCallToActionLabelOffset;
@property(retain, nonatomic) SBUILegibilityLabel *alternateCallToActionLabel; // @synthesize alternateCallToActionLabel=_alternateCallToActionLabel;
@property(retain, nonatomic) SBUICallToActionLabel *callToActionLabel; // @synthesize callToActionLabel=_callToActionLabel;
@property(readonly, nonatomic) SBShakableView *callToActionShakeView; // @synthesize callToActionShakeView=_callToActionShakeView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_updateViewsForLegibilitySettings;
- (void)updatePageControl;
- (void)_layoutPageControl;
- (void)_layoutStatusTextView;
- (void)_layoutCallToActionView;
- (void)_addPageControl;
- (void)_addShakeView;
- (void)updateForLegibilitySettings:(id)arg1;
- (id)presentationRegions;
- (id)initWithFrame:(struct CGRect)arg1;

@end

