//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SBDashBoardNotificationAdjunctListViewController;

@protocol SBDashBoardNotificationAdjunctListViewControllerDelegate
- (void)adjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1 didUpdateWithSize:(struct CGSize)arg2;
- (double)interItemSpacingToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
- (struct UIEdgeInsets)insetMarginsToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
- (struct CGSize)sizeToMimicForAdjunctListViewController:(SBDashBoardNotificationAdjunctListViewController *)arg1;
@end

