//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIVibrantButton.h"

@class SBWallpaperEffectView;

@interface SBDashBoardVibrantWallpaperButton : SBUIVibrantButton
{
    SBWallpaperEffectView *_effectView;
}

@property(readonly, nonatomic) SBWallpaperEffectView *effectView; // @synthesize effectView=_effectView;
- (void).cxx_destruct;
- (void)_updateVibrancy;
- (void)setLegibilitySettings:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

