//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDashBoardQuickActionsDelegate.h"
#import "SBUIFlashlightObserver.h"

@class NSString, SBDashBoardViewController, SBUIFlashlightController;

@interface SBDashBoardQuickActionsViewController : SBDashBoardViewControllerBase <SBDashBoardQuickActionsDelegate, SBUIFlashlightObserver>
{
    SBUIFlashlightController *_flashlight;
    SBDashBoardViewController *_dashBoardViewController;
}

+ (Class)viewClass;
+ (_Bool)deviceSupportsButtons;
@property(nonatomic) __weak SBDashBoardViewController *dashBoardViewController; // @synthesize dashBoardViewController=_dashBoardViewController;
- (void).cxx_destruct;
- (void)_featureLockStateDidChangeNotification:(id)arg1;
- (void)_deviceBlockStateDidChangeNotification:(id)arg1;
- (void)_updateState;
- (_Bool)_isFlashlightOn;
- (void)_tearDownFlashlight;
- (void)_tearDownFlashlightIfOff;
- (void)_setupFlashlight;
- (_Bool)_supportsCamera;
- (void)_resetIdleTimer;
- (void)_toggleFlashlight;
- (void)_launchCamera;
- (void)touchEndedForButton:(id)arg1;
- (void)fireActionForButton:(id)arg1;
- (void)touchBeganForButton:(id)arg1;
- (_Bool)isPortrait;
- (_Bool)allowsCameraPress;
- (_Bool)hasCamera;
- (_Bool)allowsFlashlight;
- (_Bool)hasFlashlight;
- (void)flashlightOverheatedDidChange:(_Bool)arg1;
- (void)flashlightAvailabilityDidChange:(_Bool)arg1;
- (void)flashlightLevelDidChange:(unsigned long long)arg1;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationType;
- (long long)presentationStyle;
- (long long)presentationPriority;
- (id)quickActionsViewIfLoaded;
- (id)quickActionsView;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

