//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardHostedAppViewController.h"

@interface SBDashBoardSlidingAppViewController : SBDashBoardHostedAppViewController
{
}

- (long long)presentationTransition;
- (void)performCustomTransitionToVisible:(_Bool)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

