//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWallpaperEffectView.h"

@class SBUIBackgroundView;

@interface SBDashBoardWallpaperEffectView : SBWallpaperEffectView
{
    SBUIBackgroundView *_backgroundView;
}

- (void).cxx_destruct;
- (void)setBackgroundStyle:(long long)arg1;
- (void)layoutSubviews;
- (void)didAddSubview:(id)arg1;
- (id)initWithWallpaperVariant:(long long)arg1 transformOptions:(unsigned long long)arg2;

@end

