//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SBDashBoardLockProviding <NSObject>
@property(readonly, nonatomic, getter=isLocked) _Bool locked;
- (_Bool)unlockFromSource:(int)arg1;
@end

