//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardPageViewBase.h"

@class UIScrollView, UIView, UIViewController<SBDashBoardPageViewControllerProtocol>;

@interface SBDashBoardTodayPageView : SBDashBoardPageViewBase
{
    UIViewController<SBDashBoardPageViewControllerProtocol> *_pageViewController;
    UIView *_todayView;
    UIScrollView *_widgetMajorScrollView;
    double _navigationBarTopInset;
}

@property(nonatomic) double navigationBarTopInset; // @synthesize navigationBarTopInset=_navigationBarTopInset;
@property(retain, nonatomic) UIScrollView *widgetMajorScrollView; // @synthesize widgetMajorScrollView=_widgetMajorScrollView;
@property(retain, nonatomic) UIView *todayView; // @synthesize todayView=_todayView;
- (void)setPageViewController:(id)arg1;
- (id)pageViewController;
- (void).cxx_destruct;
- (void)_updateContentInsetsForScrollView:(id)arg1 snapsToRestingPositions:(_Bool)arg2;
- (void)_layoutTodayView;
- (void)updateContentInsets;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

