//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBDashBoardAction;

@protocol SBDashBoardActionHandling <NSObject>
- (void)handleAction:(SBDashBoardAction *)arg1 fromSender:(id <SBDashBoardParticipating>)arg2;
@end

