//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardActionHandling.h"
#import "SBDashBoardViewControlling.h"

@class BSAnimationSettings, SBDashBoardAppearance, SBDashBoardBehavior, SBDashBoardPresentation;

@protocol SBDashBoardViewPresenting <SBDashBoardViewControlling, SBDashBoardActionHandling>
@property(readonly, copy, nonatomic) SBDashBoardPresentation *externalPresentation;
@property(readonly, copy, nonatomic) SBDashBoardBehavior *activeBehavior;
@property(readonly, copy, nonatomic) SBDashBoardAppearance *activeAppearance;
- (void)updateAppearanceForController:(id <SBDashBoardViewControlling>)arg1 withAnimationSettings:(BSAnimationSettings *)arg2 completion:(void (^)(_Bool))arg3;
- (void)updateAppearanceForController:(id <SBDashBoardViewControlling>)arg1;
- (void)updateBehaviorForController:(id <SBDashBoardViewControlling>)arg1;
@end

