//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBDashBoardScrollGestureController, UIGestureRecognizer;

@protocol SBDashBoardScrollGestureControllerDelegate <NSObject>
- (_Bool)controller:(SBDashBoardScrollGestureController *)arg1 shouldAllowPanScrollingWithSystemGestureRecognizer:(UIGestureRecognizer *)arg2;

@optional
- (void)controllerDidCancelHorizontalScrolling:(SBDashBoardScrollGestureController *)arg1;
- (void)controllerWillCancelHorizontalScrolling:(SBDashBoardScrollGestureController *)arg1;
@end

