//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneViewController.h"

#import "SBDeviceApplicationSceneViewControlling.h"

@class NSString, SBDeviceApplicationSceneView, SBSceneHandle, UIStatusBar, UIView;

@interface SBDeviceApplicationSceneViewController : SBApplicationSceneViewController <SBDeviceApplicationSceneViewControlling>
{
    UIStatusBar *_fakeStatusBar;
    long long _statusBarAnimationsInFlight;
    _Bool _statusBarHidden;
    double _statusBarAlpha;
}

@property(nonatomic) double statusBarAlpha; // @synthesize statusBarAlpha=_statusBarAlpha;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
- (void).cxx_destruct;
- (void)cleanupAnimationContext:(id)arg1;
- (void)executeAnimationContext:(id)arg1;
- (id)prepareAnimationToStatusBarHidden:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithSceneHandle:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) long long contentInterfaceOrientation;
@property(readonly, nonatomic) struct CGSize contentReferenceSize;
@property(retain, nonatomic) UIView *customContentView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long displayMode;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) id <SBScenePlaceholderContentContext> placeholderContentContext;
@property(readonly, nonatomic) SBSceneHandle *sceneHandle;
@property(readonly, nonatomic, getter=_sceneView) SBDeviceApplicationSceneView *sceneView; // @dynamic sceneView;
@property(readonly) Class superclass;

@end

