//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIdleTimerBase.h"

@interface SBDisabledIdleTimer : SBIdleTimerBase
{
    _Bool _activated;
}

- (void)setActivated:(_Bool)arg1;
- (_Bool)isActivated;
- (void)reset;
- (_Bool)isDisabled;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;

@end

