//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDisplayObserving.h"

@class NSMutableDictionary, NSString, SBMainDisplaySceneManager, SBMainWorkspace;

@interface SBExternalDisplayManager : NSObject <FBSDisplayObserving>
{
    SBMainWorkspace *_mainWorkspace;
    SBMainDisplaySceneManager *_mainDisplaySceneManager;
    NSMutableDictionary *_displayToControllerMap;
}

- (void).cxx_destruct;
- (void)displayMonitor:(id)arg1 willDisconnectIdentity:(id)arg2;
- (void)displayMonitor:(id)arg1 didUpdateIdentity:(id)arg2 withConfiguration:(id)arg3;
- (void)displayMonitor:(id)arg1 didConnectIdentity:(id)arg2 withConfiguration:(id)arg3;
- (id)initWithMainWorkspace:(id)arg1 andMainSceneManager:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

