//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BSAbstractDefaultDomain.h"

@class NSArray, NSString;

@interface SBExternalCarrierDefaults : BSAbstractDefaultDomain
{
}

- (void)_bindAndRegisterDefaults;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) _Bool canReinitiateActivation; // @dynamic canReinitiateActivation;
@property(readonly, nonatomic) NSString *carrierName; // @dynamic carrierName;
@property(readonly, nonatomic) NSString *customerServicePhoneNumber; // @dynamic customerServicePhoneNumber;
@property(readonly, nonatomic) NSArray *disabledApplicationIDs; // @dynamic disabledApplicationIDs;
@property(readonly, nonatomic) NSString *homeCountryCode; // @dynamic homeCountryCode;
@property(readonly, nonatomic) _Bool showClass0SMSFromField; // @dynamic showClass0SMSFromField;
@property(readonly, nonatomic) NSArray *ussdFilterSometimesStrings; // @dynamic ussdFilterSometimesStrings;
@property(readonly, nonatomic) NSArray *ussdFilterStrings; // @dynamic ussdFilterStrings;

@end

