//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBFloatingDockViewController, SBFolderController;

@protocol SBFloatingDockViewControllerDelegate <NSObject>
- (void)floatingDockViewController:(SBFloatingDockViewController *)arg1 willPerformTransitionWithFolder:(SBFolderController *)arg2 presenting:(_Bool)arg3 withTransitionCoordinator:(id <SBViewControllerTransitionCoordinator>)arg4;
- (void)floatingDockViewController:(SBFloatingDockViewController *)arg1 didChangeContentHeight:(double)arg2;
- (void)floatingDockViewController:(SBFloatingDockViewController *)arg1 wantsToBePresented:(_Bool)arg2;
@end

