//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBFluidSwitcherGestureExclusionTrapezoid : NSObject
{
    _Bool _allowHorizontalSwipesOutsideTrapezoid;
    double _baseHeight;
    double _trapezoidHeight;
    double _adjacentBaseXDistanceFromEdge;
    double _opposingBaseXDistanceFromEdge;
}

+ (id)exclusionTrapezoidWithBaseHeight:(double)arg1 trapezoidHeight:(double)arg2 adjacentBaseXDistanceFromEdge:(double)arg3 opposingBaseXDistanceFromEdge:(double)arg4 allowHorizontalSwipesOutsideTrapezoid:(_Bool)arg5;
@property(nonatomic) _Bool allowHorizontalSwipesOutsideTrapezoid; // @synthesize allowHorizontalSwipesOutsideTrapezoid=_allowHorizontalSwipesOutsideTrapezoid;
@property(nonatomic) double opposingBaseXDistanceFromEdge; // @synthesize opposingBaseXDistanceFromEdge=_opposingBaseXDistanceFromEdge;
@property(nonatomic) double adjacentBaseXDistanceFromEdge; // @synthesize adjacentBaseXDistanceFromEdge=_adjacentBaseXDistanceFromEdge;
@property(nonatomic) double trapezoidHeight; // @synthesize trapezoidHeight=_trapezoidHeight;
@property(nonatomic) double baseHeight; // @synthesize baseHeight=_baseHeight;
- (_Bool)shouldBeginGestureAtStartingPoint:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2 bounds:(struct CGRect)arg3;
- (id)debugView;

@end

