//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BSDescriptionProviding.h"
#import "BSUIScrollViewDelegate.h"
#import "CCUIModularControlCenterCardViewControllerDelegate.h"
#import "SBAppSwitcherSnapshotImageCacheDelegate.h"
#import "SBFluidSwitcherGestureManagerDelegate.h"
#import "SBFluidSwitcherGestureWorkspaceTransactionDelegate.h"
#import "SBFluidSwitcherItemContainerDelegate.h"
#import "SBFluidSwitcherPageContentViewProviderDelegate.h"
#import "SBIconViewObserver.h"
#import "SBMainAppSwitcherContentViewControlling.h"
#import "SBReachabilityObserver.h"
#import "SBSearchGestureObserver.h"
#import "UIGestureRecognizerDelegate.h"

@class BSTimer, CCUIModularControlCenterCardViewController, FBDisplayLayoutElement, FBUIApplicationSceneDeactivationAssertion, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SBAppStatusBarSettingsAssertion, SBAppSwitcherScrollView, SBAppSwitcherSettings, SBAppSwitcherSnapshotImageCache, SBAsynchronousRenderingAssertion, SBBestAppSuggestion, SBControlCenterSystemAgent, SBFloatingDockBehaviorAssertion, SBFluidSwitcherGestureManager, SBFluidSwitcherLayoutContext, SBFluidSwitcherPageContentViewProvider, SBHomeGrabberSettings, SBIconView, SBOrientationTransformWrapperView, SBWindowSelfHostWrapper, SBWorkspaceApplicationSceneTransitionContext, UITapGestureRecognizer, UIView;

@interface SBFluidSwitcherViewController : UIViewController <SBFluidSwitcherPageContentViewProviderDelegate, SBAppSwitcherSnapshotImageCacheDelegate, BSUIScrollViewDelegate, SBFluidSwitcherItemContainerDelegate, SBIconViewObserver, SBFluidSwitcherGestureManagerDelegate, CCUIModularControlCenterCardViewControllerDelegate, BSDescriptionProviding, UIGestureRecognizerDelegate, SBSearchGestureObserver, SBReachabilityObserver, SBMainAppSwitcherContentViewControlling, SBFluidSwitcherGestureWorkspaceTransactionDelegate>
{
    SBWindowSelfHostWrapper *_sceneLayoutWindowHostWrapper;
    SBOrientationTransformWrapperView *_sceneLayoutPortraitContentWrapper;
    SBWindowSelfHostWrapper *_switcherWindowHostWrapper;
    struct _NSRange _visibleItemRange;
    struct CGPoint _scrollViewLastContentOffset;
    _Bool _scrollViewLastScrolledForward;
    NSMutableDictionary *_insertionRemovalContextByAppLayout;
    NSArray *_appLayoutOrderPriorToRemovals;
    SBFluidSwitcherPageContentViewProvider *_pageContentViewProvider;
    SBAppSwitcherSnapshotImageCache *_snapshotCache;
    SBAppSwitcherSettings *_settings;
    NSMutableSet *_asynchronousRenderingAssertions;
    _Bool _asynchronousRenderingTemporarilyDisabled;
    SBAsynchronousRenderingAssertion *_gestureAsyncRenderingAssertion;
    BSTimer *_gestureAsyncRenderingAssertionAnimationInvalidationTimer;
    SBAsynchronousRenderingAssertion *_modeAsyncRenderingAssertion;
    BSTimer *_modeAsyncRenderingAssertionAnimationInvalidationTimer;
    FBUIApplicationSceneDeactivationAssertion *_modeResignActiveAssertion;
    SBFluidSwitcherGestureManager *_gestureManager;
    SBWorkspaceApplicationSceneTransitionContext *_pendingTransitionContext;
    FBDisplayLayoutElement *_controlCenterLayoutElement;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    UITapGestureRecognizer *_dismissTapGestureRecognizer;
    UIView *_dimmingView;
    _Bool _appKillingModeEnabled;
    UIView *_crossfadeSnapshotView;
    UIView *_hitTestBlockerView;
    _Bool _controlCenterVisible;
    _Bool _reachabilityActive;
    id <SBMainAppSwitcherContentViewControllerDelegate> _delegate;
    id <SBMainAppSwitcherContentViewControllerDataSource> _dataSource;
    SBBestAppSuggestion *_bestAppSuggestion;
    SBAppSwitcherScrollView *_scrollView;
    UIView *_contentView;
    id <SBFluidSwitcherPersonality> _switcherPersonality;
    SBFluidSwitcherLayoutContext *_layoutContext;
    NSMutableDictionary *_visibleItemContainers;
    NSMutableArray *_hiddenRecycledItemContainers;
    SBIconView *_hiddenIconView;
    SBFloatingDockBehaviorAssertion *_switcherFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_zoomDownFloatingDockBehaviorAssertion;
    CCUIModularControlCenterCardViewController *_controlCenterViewController;
    SBControlCenterSystemAgent *_controlCenterSystemAgent;
    SBHomeGrabberSettings *_grabberSettings;
}

+ (Class)defaultSwitcherPersonalityClass;
@property(nonatomic, getter=isReachabilityActive) _Bool reachabilityActive; // @synthesize reachabilityActive=_reachabilityActive;
@property(retain, nonatomic) SBHomeGrabberSettings *grabberSettings; // @synthesize grabberSettings=_grabberSettings;
@property(nonatomic, getter=isControlCenterVisible) _Bool controlCenterVisible; // @synthesize controlCenterVisible=_controlCenterVisible;
@property(retain, nonatomic) SBControlCenterSystemAgent *controlCenterSystemAgent; // @synthesize controlCenterSystemAgent=_controlCenterSystemAgent;
@property(retain, nonatomic) CCUIModularControlCenterCardViewController *controlCenterViewController; // @synthesize controlCenterViewController=_controlCenterViewController;
@property(retain, nonatomic) SBFloatingDockBehaviorAssertion *zoomDownFloatingDockBehaviorAssertion; // @synthesize zoomDownFloatingDockBehaviorAssertion=_zoomDownFloatingDockBehaviorAssertion;
@property(retain, nonatomic) SBFloatingDockBehaviorAssertion *switcherFloatingDockBehaviorAssertion; // @synthesize switcherFloatingDockBehaviorAssertion=_switcherFloatingDockBehaviorAssertion;
@property(retain, nonatomic) SBIconView *hiddenIconView; // @synthesize hiddenIconView=_hiddenIconView;
@property(retain, nonatomic) NSMutableArray *hiddenRecycledItemContainers; // @synthesize hiddenRecycledItemContainers=_hiddenRecycledItemContainers;
@property(retain, nonatomic) NSMutableDictionary *visibleItemContainers; // @synthesize visibleItemContainers=_visibleItemContainers;
@property(retain, nonatomic) SBFluidSwitcherLayoutContext *layoutContext; // @synthesize layoutContext=_layoutContext;
@property(retain, nonatomic) id <SBFluidSwitcherPersonality> switcherPersonality; // @synthesize switcherPersonality=_switcherPersonality;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) SBAppSwitcherScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) SBBestAppSuggestion *bestAppSuggestion; // @synthesize bestAppSuggestion=_bestAppSuggestion;
@property(nonatomic) __weak id <SBMainAppSwitcherContentViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SBMainAppSwitcherContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reduceMotionStatusDidChange:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_updateWallpaperStyle;
- (void)_handleDismissTapGesture:(id)arg1;
- (id)geometricallyVisibleItemContainers;
- (_Bool)_isLayoutStateSwitcher:(id)arg1 allowTransitions:(_Bool)arg2;
- (id)_activeAppLayout;
- (id)_opacitySettings;
- (id)_layoutSettings;
- (void)_updateHomeGrabberForEnvironmentMode:(long long)arg1 animated:(_Bool)arg2;
- (void)_updateSpringBoardStatusBarAssertionAnimated:(_Bool)arg1;
- (void)_updateSceneLayoutViewControllerAppStatusBarHidden;
- (long long)_insertionRemovalAdjustmentForIndexOfItemBeingMoved:(unsigned long long)arg1;
- (void)_endAnimatedInsertionOrRemovalOfAppLayout:(id)arg1;
- (void)_beginAnimatedInsertionOrRemovalOfAppLayout:(id)arg1 atIndex:(unsigned long long)arg2 insertion:(_Bool)arg3;
- (id)_appLayoutForAlert:(id)arg1;
- (id)_appLayoutForItemContainerAtLocation:(struct CGPoint)arg1;
- (id)_itemContainerAtLocation:(struct CGPoint)arg1;
- (void)_scrollToAppLayout:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_setWallpaperScale:(double)arg1 withMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_setContentDimmingAlpha:(double)arg1 withMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_setContentViewAlpha:(double)arg1 withMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_setScrollViewContentOffset:(struct CGPoint)arg1 withMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)setAppKillingModeEnabled:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isAppKillingModeEnabled) _Bool appKillingModeEnabled;
- (long long)homeScreenInterfaceOrientation;
- (long long)switcherInterfaceOrientation;
- (double)minimumVerticalTranslationForKillingOfContainer:(id)arg1;
- (void)scrollViewKillingProgressUpdated:(double)arg1 ofContainer:(id)arg2;
- (struct CGRect)frameForPageViewOfContainer:(id)arg1 fullyPresented:(_Bool)arg2;
- (_Bool)shouldShowIconAndLabelOfContainer:(id)arg1;
- (void)selectedAppLayoutOfContainer:(id)arg1;
- (_Bool)canSelectAppLayoutOfContainer:(id)arg1 numberOfTaps:(long long)arg2;
- (void)killAppLayoutOfContainer:(id)arg1 withVelocity:(double)arg2 forReason:(long long)arg3;
- (_Bool)isAppLayoutOfContainerRemovable:(id)arg1;
- (id)defaultAppLayoutsForImageCache:(id)arg1;
- (double)scaleForDownscaledSnapshotsForImageCache:(id)arg1;
- (long long)orientationForSnapshotOfAppLayout:(id)arg1 inImageCache:(id)arg2;
- (id)highPriorityAppLayoutsForImageCache:(id)arg1;
- (_Bool)biasForwardForImageCache:(id)arg1;
- (struct _NSRange)visibleAppLayoutRangeForImageCache:(id)arg1;
- (id)appLayoutsForImageCache:(id)arg1;
- (unsigned long long)numberOfAppLayoutsToCacheForImageCache:(id)arg1;
- (id)containerViewControllerForPageViewFromProvider:(id)arg1;
- (struct CGSize)sizeForAppLayout:(id)arg1 fromProvider:(id)arg2;
- (long long)orientationForPageViewFromProvider:(id)arg1;
- (struct CGPoint)_scrollView:(id)arg1 adjustedOffsetForOffset:(struct CGPoint)arg2 translation:(struct CGPoint)arg3 startPoint:(struct CGPoint)arg4 locationInView:(struct CGPoint)arg5 horizontalVelocity:(inout double *)arg6 verticalVelocity:(inout double *)arg7;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1 withContext:(CDStruct_3b09cf25)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_evaluateAsynchronousRenderingEnablement;
- (_Bool)_deviceSupportsTrueAsynchronousRendering;
- (void)_disableAsynchronousRenderingForNextCommit;
- (void)_reqlinquishAsynchronousRenderingAssertion:(id)arg1;
- (void)_acquireAsynchronousRenderingAssertion:(id)arg1;
- (void)_cancelScrolling;
- (double)_killGestureHysteresis;
- (id)_itemContainerForAppLayoutIfExists:(id)arg1;
- (void)_applyStyleToItemContainer:(id)arg1 withMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_applyStyleToVisibleItemContainersWithMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateStyleWithBehaviorMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (struct CGPoint)_clipContentOffsetToBeWithinContentSize:(struct CGPoint)arg1;
- (void)_updateScrollViewContentOffsetToBeWithinContentSizeAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateScrollViewContentOffsetToFocusIndex:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)_anyAppLayoutInvolvedInInsertionOrRemoval;
- (_Bool)_appLayoutIsInvolvedInInsertionOrRemoval:(id)arg1;
- (_Bool)_appLayoutWantsToBeKeptInViewHierarchy:(id)arg1;
- (void)_setSnapshotCachingEnabled:(_Bool)arg1;
- (void)_addVisibleItemContainerForAppLayout:(id)arg1;
- (_Bool)_removeVisibleItemContainerForAppLayout:(id)arg1;
- (_Bool)_shouldAnimateCrossfade;
- (void)_performCrossfadeIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)_prepareForCrossfadeIfNeeded;
- (void)_updateVisibleItems;
- (void)_ensureCardSubviewOrdering;
- (void)_updateScrollViewSizeAndSpacing;
- (void)_layoutControlCenterWithMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_layoutAppLayout:(id)arg1 mode:(long long)arg2 behaviorMode:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_layoutVisibleItemsWithBehaviorMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_layoutContentViewWithBehaviorMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateLayoutWithBehaviorMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateVisibleItemsLayoutAndStyleWithBehaviorMode:(long long)arg1 insertionRemovalLayoutParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_updateVisibleItemsLayoutAndStyleWithBehaviorMode:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateDockLayout;
- (void)_updateFloatingDockBehaviorAssertion;
- (void)viewWillLayoutSubviews;
- (_Bool)dismissControlCenterPresentedContent;
- (void)closeControlCenterModule;
- (void)respondToSwitcherModelUpdate;
- (void)removeAppLayout:(id)arg1 forReason:(long long)arg2 modelMutationBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)insertAppLayout:(id)arg1 atIndex:(unsigned long long)arg2 modelMutationBlock:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (id)obscuringBackgroundViewForControlCenterViewController:(id)arg1;
- (double)statusTextHeightForControlCenterViewController:(id)arg1;
- (void)controlCenterViewControllerDidFinishUserInteractionWithModule:(id)arg1;
- (void)controlCenterViewControllerDidBeginUserInteractionWithModule:(id)arg1;
- (long long)interfaceOrientationForControlCenterViewController:(id)arg1;
- (void)handleReachabilityModeDeactivated;
- (void)handleReachabilityModeActivated;
- (void)iconViewWasRecycled:(id)arg1;
- (void)searchGesture:(id)arg1 startedShowing:(_Bool)arg2;
- (void)searchGesture:(id)arg1 changedPercentComplete:(double)arg2;
- (void)_stopHostingSwitcherWindowInHomeScreen;
- (void)_hostSwitcherWindowInHomeScreenForZoomDownIfNecessary;
- (void)_updateIconZoomDownDockAssertionIfNecessary;
- (void)_unhideHiddenIconViewAnimated:(_Bool)arg1;
- (void)_updateIconViewForIconZoomAnimated:(_Bool)arg1;
- (void)_updateIconViewForIconZoom;
- (_Bool)_itemContainerOverlapsFloatingDock:(id)arg1;
- (void)_asyncManageDockIconZoomZOrderWithDockBelowSwitcherHandler:(CDUnknownBlockType)arg1;
- (id)_appLayoutToMakeVisibleBeforePerformingTransitionWithContext:(id)arg1;
- (id)defaultTransitionAnimationSettings;
- (void)_performContentViewScaleAnimationForDosido;
- (void)performTransitionWithContext:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_sendViewDismissingToPageViewsForTransitionRequest:(id)arg1;
- (void)_sendViewPresentingToPageViewsForTransitionRequest:(id)arg1;
- (void)_updateLayoutForInterfaceOrientation:(long long)arg1 force:(_Bool)arg2;
- (void)_updateSceneLayoutWindowHostWrapperViewForTransitionWithContext:(id)arg1;
- (void)_updateSceneViewBackgroundMaterial;
- (void)_hidePreviousLayoutElementsViewControllers;
- (_Bool)_isExternallyDrivenLayoutStateTransition:(id)arg1;
- (void)sceneLayoutControllerDidEndLayoutStateTransition:(id)arg1 wasInterrupted:(_Bool)arg2;
- (void)sceneLayoutController:(id)arg1 didBeginLayoutStateTransitionWithContext:(id)arg2;
- (void)forceUpdateInterfaceOrientation:(long long)arg1;
- (_Bool)isPerformingAppZoomUpTransition;
- (_Bool)isUserInteractionEnabled;
- (_Bool)isDisplayingContent;
- (_Bool)handleHomeButtonSinglePressUp;
- (_Bool)shouldUpdateRecentsForTransitionWithContext:(id)arg1 transitionCompleted:(_Bool)arg2;
- (_Bool)shouldUpdateContentOrientationForTransitionWithContext:(id)arg1;
- (double)minimumHomeScreenScale;
- (_Bool)hasInteractiveContentAtBottomOfScreen;
- (double)switcherCardScale;
- (double)snapshotScale;
- (void)_updateScrollViewContentOffsetForActiveGestureWithMode:(long long)arg1;
- (void)fluidSwitcherGestureTransaction:(id)arg1 didEndGesture:(id)arg2;
- (void)fluidSwitcherGestureTransaction:(id)arg1 didUpdateGesture:(id)arg2;
- (void)fluidSwitcherGestureTransaction:(id)arg1 didBeginGesture:(id)arg2;
- (void)gestureManager:(id)arg1 didEndGestureTransaction:(id)arg2;
- (void)gestureManager:(id)arg1 didBeginGestureTransaction:(id)arg2;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)_sendControlCenterViewControllerAppearanceCallbacks;
- (void)_setupControlCenterViewController;
- (void)_setupSceneLayoutWindowHostWrapper;
- (void)_setScrollViewPersonalitySettings;
- (void)_setupContentAndTransientViews;
- (void)_resetLastScrollViewState;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidLoad;
- (void)dealloc;
- (void)willMoveToParentViewController:(id)arg1;
- (id)initWithSwitcherPersonality:(id)arg1;
- (id)init;
@property(readonly, nonatomic) NSArray *appLayouts;
- (id)_displayItemFromLayoutElementWithIdentifier:(id)arg1;
- (struct CGRect)_iconImageFrameForIconView:(id)arg1;
- (id)_iconViewForDisplayItem:(id)arg1 isVisible:(_Bool *)arg2;
- (long long)_floatingDockIconLocationForTransitionSource:(long long)arg1;
- (id)_iconForApplicationSceneEntity:(id)arg1;
- (double)defaultHomeScreenIconCornerRadius;
- (struct CGSize)defaultHomeScreenIconSize;
- (double)iconCornerRadiusForAppLayout:(id)arg1;
- (struct CGRect)iconImageFrameForHomeScreenIconZoom;
- (struct CGRect)_uncachedIconImageFrameForAppLayout:(id)arg1;
- (id)iconViewForAppLayout:(id)arg1;
- (id)activatingDisplayItemForAppLayout:(id)arg1;
@property(readonly, nonatomic) long long layoutMode;
- (id)appLayoutToScrollToDuringTransition:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

