//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFTouchPassThroughView.h"

@class SBDockIconListView, SBFloatingDockPlatterView, UIView;

@interface SBFloatingDockView : SBFTouchPassThroughView
{
    SBDockIconListView *_userIconListView;
    SBDockIconListView *_recentIconListView;
    unsigned long long _minimumUserIconSpaces;
    SBFloatingDockPlatterView *_mainPlatterView;
    UIView *_dividerView;
    double _iconContentScale;
}

+ (void)getMetrics:(CDStruct_c0971cc5 *)arg1 forBounds:(struct CGRect)arg2 numberOfUserIcons:(unsigned long long)arg3 numberOfRecentIcons:(unsigned long long)arg4;
+ (double)contentHeightForBounds:(struct CGRect)arg1 mainPlatterViewFrame:(struct CGRect)arg2;
+ (struct CGSize)maximumIconSize;
+ (double)minimumPlatterMargin;
+ (double)maximumPlatterHeight;
+ (double)maximumInterIconSpacing;
+ (double)maximumDockContinuousCornerRadius;
+ (double)_referenceInterIconSpacing;
+ (struct CGSize)_referenceIconSize;
@property(nonatomic) double iconContentScale; // @synthesize iconContentScale=_iconContentScale;
@property(retain, nonatomic) UIView *dividerView; // @synthesize dividerView=_dividerView;
@property(retain, nonatomic) SBFloatingDockPlatterView *mainPlatterView; // @synthesize mainPlatterView=_mainPlatterView;
@property(nonatomic) unsigned long long minimumUserIconSpaces; // @synthesize minimumUserIconSpaces=_minimumUserIconSpaces;
@property(retain, nonatomic) SBDockIconListView *recentIconListView; // @synthesize recentIconListView=_recentIconListView;
@property(retain, nonatomic) SBDockIconListView *userIconListView; // @synthesize userIconListView=_userIconListView;
- (void).cxx_destruct;
- (void)bounce;
- (void)layoutSubviews;
- (void)getMetrics:(CDStruct_c0971cc5 *)arg1 forBounds:(struct CGRect)arg2;
@property(readonly, nonatomic) double interIconSpacing;
- (double)iconContentScaleForNumberOfUserIcons:(unsigned long long)arg1;
- (double)contentHeightForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) double contentHeight;
- (struct UIEdgeInsets)platterShadowOutsetsForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) struct UIEdgeInsets platterShadowOutsets;
@property(nonatomic) _Bool hasPlatterShadow;
@property(readonly, nonatomic) struct CGRect platterFrame;
- (id)initWithFrame:(struct CGRect)arg1;

@end

