//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBFolderView, SBIconListView, SBIconView, UIDragItem, UIDropProposal, UIPinchGestureRecognizer, UITargetedDragPreview;

@protocol SBFolderViewDelegate <NSObject>
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 springLoadedInteractionForIconDragDidCompleteOnIconView:(SBIconView *)arg3;
- (_Bool)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 shouldAllowSpringLoadedInteractionForIconDragOnIconView:(SBIconView *)arg3;
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 iconDragItem:(UIDragItem *)arg3 willAnimateDropWithAnimator:(id <UIDragAnimating>)arg4;
- (UITargetedDragPreview *)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 previewForDroppingIconDragItem:(UIDragItem *)arg3 proposedPreview:(UITargetedDragPreview *)arg4;
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 performIconDrop:(id <UIDropSession>)arg3;
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidExit:(id <UIDropSession>)arg3;
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 iconDropSession:(id <UIDropSession>)arg3 didPauseAtLocation:(struct CGPoint)arg4;
- (UIDropProposal *)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidUpdate:(id <UIDropSession>)arg3;
- (void)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidEnter:(id <UIDropSession>)arg3;
- (_Bool)folderView:(SBFolderView *)arg1 iconListView:(SBIconListView *)arg2 canHandleIconDropSession:(id <UIDropSession>)arg3;
- (void)folderViewShouldBeginEditing:(SBFolderView *)arg1;
- (void)folderViewShouldClose:(SBFolderView *)arg1 withPinchGesture:(UIPinchGestureRecognizer *)arg2;
- (void)folderViewDidEndScrolling:(SBFolderView *)arg1;
- (void)folderViewWillBeginScrolling:(SBFolderView *)arg1;
- (void)folderView:(SBFolderView *)arg1 currentPageIndexDidChange:(long long)arg2;
- (Class)iconListViewClassForFolderView:(SBFolderView *)arg1;

@optional
- (void)forceUpdateContentOverlayInsetsToContentOverlayInsets:(struct UIEdgeInsets)arg1;
- (struct UIEdgeInsets)contentOverlayInsetsFromParentIfAvailableForFolderView:(SBFolderView *)arg1;
- (double)minimumHomeScreenScaleForFolderView:(SBFolderView *)arg1;
- (void)folderViewDidReceiveCancelReachabilityAction:(SBFolderView *)arg1;
@end

