//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBFolder, SBFolderController, SBIconListView, SBIconView, UIDragItem, UIDropProposal, UIPinchGestureRecognizer, UITargetedDragPreview;

@protocol SBFolderControllerDelegate <NSObject>
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 springLoadedInteractionForIconDragDidCompleteOnIconView:(SBIconView *)arg3;
- (_Bool)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 shouldAllowSpringLoadedInteractionForIconDragOnIconView:(SBIconView *)arg3;
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 iconDragItem:(UIDragItem *)arg3 willAnimateDropWithAnimator:(id <UIDragAnimating>)arg4;
- (UITargetedDragPreview *)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 previewForDroppingIconDragItem:(UIDragItem *)arg3 proposedPreview:(UITargetedDragPreview *)arg4;
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 performIconDrop:(id <UIDropSession>)arg3;
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidExit:(id <UIDropSession>)arg3;
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 iconDropSession:(id <UIDropSession>)arg3 didPauseAtLocation:(struct CGPoint)arg4;
- (UIDropProposal *)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidUpdate:(id <UIDropSession>)arg3;
- (void)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 iconDropSessionDidEnter:(id <UIDropSession>)arg3;
- (_Bool)folderController:(SBFolderController *)arg1 iconListView:(SBIconListView *)arg2 canHandleIconDropSession:(id <UIDropSession>)arg3;
- (void)folderControllerDidEndScrolling:(SBFolderController *)arg1;
- (void)folderControllerWillBeginScrolling:(SBFolderController *)arg1;
- (void)folderControllerShouldEndEditing:(SBFolderController *)arg1;
- (void)folderControllerShouldBeginEditing:(SBFolderController *)arg1;
- (void)folderControllerShouldClose:(SBFolderController *)arg1 withPinchGesture:(UIPinchGestureRecognizer *)arg2;
- (void)folderController:(SBFolderController *)arg1 draggedIconShouldDropFromListView:(SBIconListView *)arg2;
- (Class)controllerClassForFolder:(SBFolder *)arg1;

@optional
- (struct UIEdgeInsets)contentOverlayInsetsFromParentIfAvailableForFolderController:(SBFolderController *)arg1;
- (void)folderControllerDidClose:(SBFolderController *)arg1;
- (void)folderControllerWillClose:(SBFolderController *)arg1;
- (void)folderControllerDidOpen:(SBFolderController *)arg1;
- (void)folderControllerWillOpen:(SBFolderController *)arg1;
- (double)minimumHomeScreenScaleForFolderController:(SBFolderController *)arg1;
- (void)folderControllerDidReceiveCancelReachabilityAction:(SBFolderController *)arg1;
@end

