//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFluidSwitcherGestureWorkspaceTransaction.h"

@interface SBGridScrunchToHomeGestureWorkspaceTransaction : SBFluidSwitcherGestureWorkspaceTransaction
{
}

- (void)_finishWithGesture:(id)arg1;
- (void)_beginWithGesture:(id)arg1;
- (long long)_gestureType;

@end

