//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIApplicationSceneClientSettings, UIApplicationSceneSettings;

@interface SBHostedAppClientSettingObserverContext : NSObject
{
    UIApplicationSceneSettings *_settings;
    UIApplicationSceneClientSettings *_updatedClientSettings;
}

@property(retain, nonatomic) UIApplicationSceneClientSettings *updatedClientSettings; // @synthesize updatedClientSettings=_updatedClientSettings;
@property(retain, nonatomic) UIApplicationSceneSettings *settings; // @synthesize settings=_settings;
- (void).cxx_destruct;

@end

