//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDropInteractionDelegate.h"

@class SBIconView;

@protocol SBIconListViewDraggingPolicyHandling <UIDropInteractionDelegate>
- (void)handleSpringLoadOnIconView:(SBIconView *)arg1;
- (_Bool)allowsSpringLoadOnIconView:(SBIconView *)arg1;
@end

