//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SBIconLabelImageParameters, UIImage, _UILegibilitySettings;

@protocol SBIconLabelView
@property(retain, nonatomic) UIImage *image;
- (void)updateIconLabelWithSettings:(_UILegibilitySettings *)arg1 imageParameters:(SBIconLabelImageParameters *)arg2;
- (id)initWithSettings:(_UILegibilitySettings *)arg1;
@end

