//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SBIconAccessoryInfoProvider <NSObject>
@property(readonly, nonatomic) long long continuityBadgeType;
@property(readonly, nonatomic, getter=isHighlighted) _Bool highlighted;
@property(readonly, nonatomic) long long location;
@end

