//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLockOverlayViewController.h"

@class SBLockScreenPlugin;

@interface SBLockScreenPluginOverlayViewController : SBLockOverlayViewController
{
    SBLockScreenPlugin *_plugin;
}

+ (_Bool)_pluginNeedsOverlay:(id)arg1;
- (void).cxx_destruct;
- (id)_newOverlayView;
- (void)loadView;
- (id)initWithPlugin:(id)arg1;

@end

