//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface SBLockOverlayViewController : UIViewController
{
    id <SBLockOverlayViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SBLockOverlayViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool shouldBeHidden;
- (id)overlayView;

@end

