//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFLockScreenDateSubtitleView.h"

#import "_UISettingsKeyObserver.h"

@class NSDate, NSString;

@interface SBLockScreenTimerView : SBFLockScreenDateSubtitleView <_UISettingsKeyObserver>
{
    NSDate *_endDate;
}

- (void).cxx_destruct;
- (id)_createReplicateView;
- (id)_timerFont;
- (id)_newTimerDialForSettings:(id)arg1;
- (void)_updateLegibilityStrength;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)updateTimerLabel;
- (void)setEndDate:(id)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

