//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBAppLayout, SBBestAppSuggestion;

@protocol SBMainAppSwitcherContentViewControllerDelegate <NSObject>
- (void)updateUserInteractionEnabledForSwitcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1;
- (unsigned long long)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 indexForBringingAppLayoutToFront:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 bringAppLayoutToFront:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 activatedBestAppSuggestion:(SBBestAppSuggestion *)arg2;
- (_Bool)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 canDeleteAppLayout:(SBAppLayout *)arg2;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 deletedAppLayout:(SBAppLayout *)arg2 forReason:(long long)arg3;
- (void)switcherContentController:(id <SBMainAppSwitcherContentViewControlling>)arg1 selectedAppLayout:(SBAppLayout *)arg2;
@end

