//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIWindow;

@interface SBMedusaController : NSObject
{
    UIWindow *_floatingDockWindow;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) UIWindow *floatingDockWindow; // @synthesize floatingDockWindow=_floatingDockWindow;
- (void).cxx_destruct;
- (id)init;
- (id)_init;

@end

