//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBMedusaDecoratedDeviceApplicationSceneViewControlling.h"

@class NSMutableArray, NSString, SBApplicationBlurContentView, SBDeviceApplicationSceneHandle, SBDeviceApplicationSceneViewController, SBNubView, SBSceneHandle, UIDropInteraction, UIView;

@interface SBMedusaDecoratedDeviceApplicationSceneViewController : UIViewController <SBMedusaDecoratedDeviceApplicationSceneViewControlling>
{
    SBDeviceApplicationSceneHandle *_deviceApplicationSceneHandle;
    long long _statusBarAreaStyle;
    double _statusBarAreaAlpha;
    _Bool _nubViewHighlighted;
    NSMutableArray *_gestureRecognizers;
    SBDeviceApplicationSceneViewController *_deviceApplicationSceneViewController;
    UIView *_rimShadowView;
    UIView *_containerView;
    UIView *_blurViewContainerView;
    UIView *_statusBarAreaView;
    SBNubView *_nubView;
    UIView *_darkenView;
    UIView *_hitTestView;
    _Bool _isBlurred;
    _Bool _isTransitioningBlur;
    SBApplicationBlurContentView *_blurView;
    double _shadowOpacity;
    double _shadowOffset;
    double _cornerRadius;
    double _darkenViewAlpha;
    UIDropInteraction *_dropInteraction;
}

+ (double)prototypeSettingsRimShadowRadius;
+ (double)prototypeSettingsRimShadowOpacity;
+ (double)prototypeSettingsDiffuseShadowRadius;
+ (double)prototypeSettingsDiffuseShadowOffset;
+ (double)prototypeSettingsDiffuseShadowOpacity;
@property(retain, nonatomic) UIDropInteraction *dropInteraction; // @synthesize dropInteraction=_dropInteraction;
@property(nonatomic) double darkenViewAlpha; // @synthesize darkenViewAlpha=_darkenViewAlpha;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity=_shadowOpacity;
- (void).cxx_destruct;
- (void)_setAbsoluteShadowRadius:(double)arg1;
- (void)_setAbsoluteShadowOffset:(struct CGSize)arg1;
- (void)_setAbsoluteDiffuseShadowOpacity:(double)arg1;
@property(retain, nonatomic, setter=_setBlurContentView:) SBApplicationBlurContentView *_blurContentView;
- (_Bool)nubViewContainsPoint:(struct CGPoint)arg1;
- (void)removeGestureRecognizer:(id)arg1;
- (void)addGestureRecognizer:(id)arg1;
- (void)loadView;
- (void)viewWillLayoutSubviews;
@property(nonatomic, getter=isNubViewHighlighted) _Bool nubViewHighlighted;
@property(nonatomic) double statusBarAreaAlpha;
- (void)cleanupAnimationContext:(id)arg1;
- (void)executeAnimationContext:(id)arg1;
- (id)prepareAnimationToStatusBarAreaStyle:(long long)arg1;
@property(nonatomic) long long statusBarAreaStyle;
- (void)containerContentWrapperInterfaceOrientationChangedTo:(long long)arg1;
- (void)setDisplayMode:(long long)arg1 animationFactory:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setContentReferenceSize:(struct CGSize)arg1 withInterfaceOrientation:(long long)arg2;
@property(readonly, nonatomic) long long contentInterfaceOrientation;
@property(readonly, nonatomic) struct CGSize contentReferenceSize;
- (void)newSnapshotViewOnQueue:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)newSnapshotView;
- (id)newSnapshot;
@property(retain, nonatomic) UIView *customContentView;
@property(retain, nonatomic) id <SBScenePlaceholderContentContext> placeholderContentContext;
@property(readonly, nonatomic) long long displayMode;
@property(readonly, nonatomic) SBSceneHandle *sceneHandle;
- (id)initWithCoder:(id)arg1;
- (void)blurApplicationContent:(_Bool)arg1 withAnimationFactory:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic, getter=isBlurred) _Bool blurred;
- (void)invalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithDeviceApplicationSceneHandle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

