//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUISettings.h"

@class SBAnimationSettings;

@interface SBMiscellaneousSystemAnimationSettings : SBUISettings
{
    float _assistantAnimationDuration;
    float _assistantDismissAnimationDurationOverApp;
    float _spotlightNoninteractiveAnimationDuration;
    SBAnimationSettings *_slideoverDosidoAnimationSettings;
    SBAnimationSettings *_crossBlurDosidoAnimationSettings;
}

+ (id)settingsControllerModule;
@property(retain, nonatomic) SBAnimationSettings *crossBlurDosidoAnimationSettings; // @synthesize crossBlurDosidoAnimationSettings=_crossBlurDosidoAnimationSettings;
@property(retain, nonatomic) SBAnimationSettings *slideoverDosidoAnimationSettings; // @synthesize slideoverDosidoAnimationSettings=_slideoverDosidoAnimationSettings;
@property(nonatomic) float spotlightNoninteractiveAnimationDuration; // @synthesize spotlightNoninteractiveAnimationDuration=_spotlightNoninteractiveAnimationDuration;
@property(nonatomic) float assistantDismissAnimationDurationOverApp; // @synthesize assistantDismissAnimationDurationOverApp=_assistantDismissAnimationDurationOverApp;
@property(nonatomic) float assistantAnimationDuration; // @synthesize assistantAnimationDuration=_assistantAnimationDuration;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

