//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCNotificationRequestContentProvider.h"

@class NCNotificationViewController;

@interface SBNotificationStaticContentProvider : NCNotificationRequestContentProvider
{
    NCNotificationViewController *_viewController;
}

@property(readonly, nonatomic) __weak NCNotificationViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)init;
- (id)initWithNotificationRequest:(id)arg1 viewController:(id)arg2;
- (id)initWithNotificationRequest:(id)arg1;

@end

