//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCNotificationDestination.h"
#import "SBNotificationExtensionVisibilityProviding.h"
#import "SBNotificationLongLookPresenting.h"

@class SBNCAlertingController;

@protocol SBNotificationDestination <NCNotificationDestination, SBNotificationExtensionVisibilityProviding, SBNotificationLongLookPresenting>
@property(nonatomic) __weak SBNCAlertingController *alertingController;
@end

