//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureRecognizerDelegate.h"

@class SBPanSystemGestureRecognizer, UITouch;

@protocol SBPanSystemGestureRecognizerDelegate <SBSystemGestureRecognizerDelegate>

@optional
- (void)panSystemGestureRecognizer:(SBPanSystemGestureRecognizer *)arg1 didReceiveInitialTouch:(UITouch *)arg2;
@end

