//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIcon.h"

@class NSArray;

@interface SBPlaceholderIcon : SBIcon
{
    id _nodeIdentifier;
    SBIcon *_icon;
    NSArray *_icons;
}

+ (id)emptyPlaceholderWithDescription:(id)arg1;
+ (id)emptyPlaceholderForRemovedIcon:(id)arg1;
+ (id)emptyPlaceholder;
+ (id)grabbedIconPlaceholderForIcons:(id)arg1;
+ (id)grabbedIconPlaceholderForIcon:(id)arg1;
+ (id)placeholderForIcon:(id)arg1;
+ (id)placeholderNodeIdentifierForIconNodeIdentifier:(id)arg1;
+ (id)placeholderNodeIdentifierForIcon:(id)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *referencedIcons;
@property(readonly, nonatomic) SBIcon *referencedIcon;
- (_Bool)isPlaceholder;
- (id)getGenericIconImage:(int)arg1;
- (_Bool)shouldCacheImageForFormat:(int)arg1;
- (id)generateIconImage:(int)arg1;
- (id)automationID;
- (id)nodeIdentifier;
- (id)_initWithNodeIdentifier:(id)arg1 icons:(id)arg2;
- (id)_initWithNodeIdentifier:(id)arg1 icon:(id)arg2;

@end

