//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSOrderedSet, NSString;

@interface SBPlatformController : NSObject
{
    NSDictionary *_defaultIconState;
    NSDictionary *_defaultStarkIconState;
    NSOrderedSet *_defaultIconStateDisplayIdentifiers;
    NSString *_localizedDeviceName;
    _Bool _supportsOpenGLES2;
    _Bool _internalInstall;
    _Bool _carrierInstall;
    _Bool _singleCoreDevice;
    _Bool _starkDevice;
    long long _medusaCapabilities;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_loadDefaultIconInfo;
- (_Bool)isiPadMini;
- (long long)medusaCapabilities;
- (_Bool)isStarkDevice;
- (_Bool)isSingleCoreDevice;
- (_Bool)isDeveloperDevice;
- (_Bool)isCarrierInstall;
- (_Bool)isInternalInstall;
- (_Bool)supportsOpenGLES2;
- (id)localizedPlatformName;
- (id)defaultIconStateDisplayIdentifiers;
- (id)defaultStarkIconState;
- (id)defaultIconState;
- (id)uniqueDeviceIdentifier;
- (id)deviceClass;
- (id)productType;
- (id)hardwareModel;
- (id)systemBuildVersion;
- (id)init;

@end

