//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIPowerDownViewDelegate.h"

@class NSString, UIView<SBUIPowerDownViewInterface>;

@protocol SBPowerDownAlertViewDelegate <SBUIPowerDownViewDelegate>
- (void)powerDownView:(UIView<SBUIPowerDownViewInterface> *)arg1 incrementValueForAggdKey:(NSString *)arg2;
@end

