//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

#import "SBPowerDownAlertViewDelegate.h"

@class NSString, SBPowerDownAlertView;

@interface SBPowerDownController : SBAlert <SBPowerDownAlertViewDelegate>
{
    id _delegate;
    SBPowerDownAlertView *_powerDownView;
    CDUnknownBlockType _orderOutCompletion;
    unsigned long long _aggdStartTime;
    int _preferredStatusBarVisibility;
}

@property(nonatomic) __weak id <SBPowerDownControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType orderOutCompletion; // @synthesize orderOutCompletion=_orderOutCompletion;
- (void).cxx_destruct;
- (long long)preferredStatusBarStyle;
- (int)_preferredStatusBarVisibility;
- (void)_endTimeTrackingAndReportWithKey:(id)arg1;
- (void)_beginTimeTracking;
- (void)_incrementCountForKey:(id)arg1;
- (void)_lockedOnTop;
- (void)_restoreIconListIfNecessary;
- (void)powerDownView:(id)arg1 incrementValueForAggdKey:(id)arg2;
- (void)powerDownViewAnimateOutCompleted:(id)arg1;
- (void)powerDownViewWillAnimateOut:(id)arg1;
- (void)powerDownViewWillAnimateIn:(id)arg1;
- (void)powerDownViewRequestPowerDown:(id)arg1;
- (void)powerDownViewRequestCancel:(id)arg1;
- (double)longPressDurationForHomeButton;
- (double)autoLockTime;
- (void)deactivate;
- (void)activate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)displayWillDisappear;
- (void)displayWillAppear;
- (_Bool)hasTranslucentBackground;
- (void)cancel;
- (void)powerDown;
- (void)orderOutWithCompletion:(CDUnknownBlockType)arg1;
- (void)orderFront;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

