//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBHardwareButtonGestureParametersProviderBase.h"

#import "SBHardwareButtonInteraction.h"
#import "SBProximitySensorManagerObserver.h"

@class BSTimer, NSString, SBProximitySensorManager;

@interface SBRecalibrateProximitySensorMultiphaseHardwareButtonInteraction : SBHardwareButtonGestureParametersProviderBase <SBProximitySensorManagerObserver, SBHardwareButtonInteraction>
{
    long long _phase;
    SBProximitySensorManager *_sensorManager;
    BSTimer *_timer;
}

@property(retain, nonatomic) BSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) SBProximitySensorManager *sensorManager; // @synthesize sensorManager=_sensorManager;
@property(nonatomic) long long phase; // @synthesize phase=_phase;
- (void).cxx_destruct;
- (void)_timerDidFire;
- (void)_transitionToPhase:(long long)arg1 timeout:(double)arg2;
- (void)_transitionToPhase:(long long)arg1;
- (id)hardwareButtonGestureParameters;
- (void)proximitySensorManager:(id)arg1 objectWithinProximityDidChange:(_Bool)arg2;
- (_Bool)disallowsLongPressForReason:(id *)arg1;
- (_Bool)disallowsTriplePressForReason:(id *)arg1;
- (_Bool)disallowsDoublePressForReason:(id *)arg1;
- (_Bool)disallowsSinglePressForReason:(id *)arg1;
- (_Bool)_disallowsAnyPressForReason:(id *)arg1;
- (_Bool)consumeSinglePressUp;
- (_Bool)consumeInitialButtonDown;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)dealloc;
- (id)initWithProximitySensorManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

