//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBGridSwitcherPersonality.h"

@interface SBReduceMotionGridSwitcherPersonality : SBGridSwitcherPersonality
{
}

- (struct CGRect)_switcherViewBounds;
- (struct CGRect)_adjustedControlCenterFrameForSwitcherBringUp:(struct CGRect)arg1;
- (struct CGRect)_adjustedFrameForSwitcherBringUp:(struct CGRect)arg1 index:(unsigned long long)arg2;
- (double)_scaleForSwipingHomeToSwitcher;
- (double)_scaleForSwipingAppUpToSwitcher;
- (double)scaleForControlCenter;
- (double)dockProgress;
- (double)switcherOpacity;
- (double)wallpaperScale;
- (double)homeScreenScale;

@end

