//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface SBSceneDataStore : NSObject
{
    NSString *_identifier;
    NSMutableDictionary *_data;
    CDUnknownBlockType _handler;
    _Bool _invalidated;
}

@property(readonly, nonatomic, getter=_isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(readonly, nonatomic, getter=_data) NSDictionary *data; // @synthesize data=_data;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)_invokeChangeHandler;
- (void)_invalidate;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)safeObjectForKey:(id)arg1 ofType:(Class)arg2;
- (id)objectForKey:(id)arg1;
- (id)_initWithIdentifier:(id)arg1 data:(id)arg2 changeHandler:(CDUnknownBlockType)arg3;

@end

