//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SBScreenWakeAnimationController;

@protocol SBScreenWakeAnimationControllerDelegate <NSObject>
- (void)screenWakeAnimationController:(SBScreenWakeAnimationController *)arg1 setRelevantViewsHidden:(_Bool)arg2 forRequester:(NSString *)arg3;
@end

