//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardHostedAppViewController.h"

@interface SBSecureAppViewController : SBDashBoardHostedAppViewController
{
}

- (void)configureDisplayLayoutElement:(id)arg1;
- (_Bool)handleEvent:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <SBSecureAppViewControllerDelegate> delegate; // @dynamic delegate;

@end

