//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@interface SBSIMLockAlertItem : SBAlertItem
{
    long long _status;
}

+ (id)alertTitleForStatus:(long long)arg1;
+ (id)alertTitleForStatus:(long long)arg1 languageCode:(id)arg2;
- (_Bool)reappearsAfterLock;
- (_Bool)reappearsAfterUnlock;
- (_Bool)pendInSetupIfNotAllowed;
- (_Bool)allowInSetup;
- (_Bool)forcesModalAlertAppearance;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (_Bool)_canShowOKButton:(_Bool)arg1;
- (_Bool)_canShowUnlockButton:(_Bool)arg1;
- (_Bool)_isBricked;
- (_Bool)_inSetup;
- (void)performUnlockAction;
- (void)trySIMUnlock;
- (void)didDeactivateForReason:(int)arg1;
- (long long)status;
- (id)alertTextForLanguageCode:(id)arg1;
- (id)alertTitleForLanguageCode:(id)arg1;
- (_Bool)canSIMUnlock;
- (id)initWithStatus:(long long)arg1;

@end

