//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBVolumePressBandit.h"

@class BSTimer, NSMutableSet, NSString, SBClawGestureLogger, SBSOSDefaults, SOSManager;

@interface SBSOSClawGestureObserver : NSObject <SBVolumePressBandit>
{
    SOSManager *_sosManager;
    _Bool _lockButtonPressedAloneWhileSOSActive;
    _Bool _sosEnabled;
    _Bool _wasSOSTiggeredByClaw;
    NSMutableSet *_activePressTypes;
    SBClawGestureLogger *_clawGestureLogger;
    id <SBSOSClawGestureObserverDelegate> _delegate;
    SBSOSDefaults *_sosDefaults;
    BSTimer *_sosTriggerTimer;
}

@property(nonatomic, getter=_wasSOSTriggeredByClaw, setter=_setWasSOSTriggeredByClaw:) _Bool wasSOSTiggeredByClaw; // @synthesize wasSOSTiggeredByClaw=_wasSOSTiggeredByClaw;
@property(retain, nonatomic) BSTimer *sosTriggerTimer; // @synthesize sosTriggerTimer=_sosTriggerTimer;
@property(nonatomic, getter=isSOSEnabled, setter=setSOSEnabled:) _Bool sosEnabled; // @synthesize sosEnabled=_sosEnabled;
@property(readonly, nonatomic) SBSOSDefaults *sosDefaults; // @synthesize sosDefaults=_sosDefaults;
@property(nonatomic) __weak id <SBSOSClawGestureObserverDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBClawGestureLogger *clawGestureLogger; // @synthesize clawGestureLogger=_clawGestureLogger;
@property(retain, nonatomic) NSMutableSet *activePressTypes; // @synthesize activePressTypes=_activePressTypes;
- (void).cxx_destruct;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)_sosInitiationStateChanged:(id)arg1;
@property(readonly, nonatomic, getter=_isSOSActivated) _Bool sosActivated;
- (_Bool)_isAutomaticCallCountdownEnabled;
- (void)_presentSOSInterface;
@property(readonly, nonatomic, getter=isClawActivated) _Bool clawActivated;
@property(nonatomic, getter=isGestureLoggingEnabled) _Bool gestureLoggingEnabled;
- (void)noteGesturePressType:(long long)arg1 withPressPhase:(long long)arg2;
- (id)_initWithSOSManager:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

