//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertWindowViewController.h"

@interface SBStarkAlertWindowViewController : SBAlertWindowViewController
{
}

- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (void)noteAlertWindow:(id)arg1 didDisplayAlert:(id)arg2;

@end

