//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SBSwitcherInsertionRemovalContext : NSObject
{
    _Bool _insertion;
    _Bool _shouldLayoutAsVisible;
    _Bool _initialVisibility;
    _Bool _finalVisibility;
    unsigned long long _direction;
    NSArray *_appLayoutsToIncludeForAnimation;
}

@property(retain, nonatomic) NSArray *appLayoutsToIncludeForAnimation; // @synthesize appLayoutsToIncludeForAnimation=_appLayoutsToIncludeForAnimation;
@property(nonatomic) _Bool finalVisibility; // @synthesize finalVisibility=_finalVisibility;
@property(nonatomic) _Bool initialVisibility; // @synthesize initialVisibility=_initialVisibility;
@property(nonatomic) _Bool shouldLayoutAsVisible; // @synthesize shouldLayoutAsVisible=_shouldLayoutAsVisible;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(nonatomic, getter=isInsertion) _Bool insertion; // @synthesize insertion=_insertion;
- (void).cxx_destruct;

@end

