//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBLockScreenManager, SBMainDisplayPolicyAggregator;

@interface SBTodayWidgetXCodeDebuggingUtility : NSObject
{
    SBLockScreenManager *_lockScreenManager;
    SBMainDisplayPolicyAggregator *_policyAggregator;
}

- (void).cxx_destruct;
- (void)_reallyLaunchTodayViewFromCurrentContextWithCompletion:(CDUnknownBlockType)arg1;
- (void)launchTodayViewFromCurrentContextWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

