//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDisplayLayoutObserver.h"
#import "_UISettingsKeyObserver.h"

@class FBSDisplayLayoutMonitor, NSObject<OS_dispatch_queue>, NSString, SBBackBoardServicesInterface, SBMedusaSettings;

@interface SBTouchRegionManager : NSObject <FBSDisplayLayoutObserver, _UISettingsKeyObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    SBBackBoardServicesInterface *_queue_bksInterface;
    FBSDisplayLayoutMonitor *_queue_displayLayoutMonitor;
    SBMedusaSettings *_medusaSettings;
    double _queue_touchRegionBuffer;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)layoutMonitor:(id)arg1 didUpdateDisplayLayout:(id)arg2 withContext:(id)arg3;
- (void)_queue_displayLayoutDidUpdate:(id)arg1;
- (id)_queue_floatingHitTestRegionForLayoutRect:(struct CGRect)arg1;
- (struct NSMutableSet *)_queue_calculateHitTestRegionsFromSceneRects:(struct NSMutableSet *)arg1;
- (struct NSMutableSet *)_queue_calculateTouchRegionsFromSceneRects:(struct NSMutableSet *)arg1;
- (id)displayLayoutMonitor;
- (void)setDisplayLayoutMonitor:(id)arg1;
- (void)setTouchRegionBuffer:(double)arg1;
- (double)touchRegionBuffer;
- (void)dealloc;
- (id)_initWithBKSInterface:(id)arg1 displayLayoutMonitor:(id)arg2 settings:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

