//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIStarkScreenAnimationController.h"

@class SBAlert, SBApplicationSceneHandle, SBDosidoAnimator, UIView;

@interface SBUIStarkDosidoAnimation : SBUIStarkScreenAnimationController
{
    UIView *_fromView;
    UIView *_toView;
    UIView *_viewToHide;
    SBAlert *_alertImpersonator;
    SBDosidoAnimator *_dosidoAnimator;
    SBApplicationSceneHandle *_impersonatedApplicationSceneHandle;
    _Bool _animationFinished;
    _Bool _fromAssistant;
}

- (void).cxx_destruct;
- (void)noteDependencyDidInvalidate;
- (void)_maybeReportAnimationFinished;
- (void)_cleanupHosting;
- (id)_animationFactory;
- (double)_animationDelay;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (id)animationSettings;
- (void)_willSetupStartDependencies;
- (void)_application:(id)arg1 processStateDidChange:(id)arg2;
- (id)_progressDependencies;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (void)dealloc;
- (id)initFromAlertImpersonator:(id)arg1 toApplicationSceneEntity:(id)arg2 starkScreenController:(id)arg3;
- (id)initFromApplicationSceneEntity:(id)arg1 toAlertImpersonator:(id)arg2 starkScreenController:(id)arg3;
- (id)initFromApplicationSceneEntity:(id)arg1 toApplicationSceneEntity:(id)arg2 starkScreenController:(id)arg3;
- (void)_commonInitFromView:(id)arg1 toView:(id)arg2 alert:(id)arg3 toDisplay:(id)arg4;

@end

