//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBCoverSheetPresentationManager, SBLockScreenUnlockRequest;

@protocol SBUILockStateProvider <NSObject>
- (void)coverSheetPresentationManager:(SBCoverSheetPresentationManager *)arg1 unlockWithRequest:(SBLockScreenUnlockRequest *)arg2 completion:(void (^)(_Bool))arg3;
- (_Bool)isUILocked;
@end

