//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureWorkspaceTransaction.h"

@class FBUIApplicationSceneDeactivationAssertion, SBApplicationBlurContentView, SBMainDisplayLayoutState, SBMainDisplaySceneLayoutViewController, SBMainWorkspaceApplicationSceneLayoutElementViewController, SBMainWorkspaceTransaction, SBPanSystemGestureRecognizer;

@interface SBUnpinSideApplicationPanSystemGestureRecognizerWorkspaceTransaction : SBSystemGestureWorkspaceTransaction
{
    SBMainDisplayLayoutState *_initialLayoutState;
    long long _initialInterfaceOrientation;
    long long _initialSpaceConfiguration;
    long long _completionFloatingConfiguration;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_primaryLayoutElementViewController;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_sideLayoutElementViewController;
    FBUIApplicationSceneDeactivationAssertion *_applicationSceneDeactivationAssertion;
    SBMainWorkspaceTransaction *_layoutStateTransitionWorkspaceTransaction;
    SBApplicationBlurContentView *_blurContentView;
    SBMainDisplaySceneLayoutViewController *_sceneLayoutViewController;
    SBPanSystemGestureRecognizer *_panSystemGestureRecognizer;
    long long _layoutRole;
}

+ (double)prototypeSettingsPinUnpinPanGestureMaximumScale;
+ (double)prototypeSettingsPinUnpinPanGestureThresholdPercentage;
+ (double)prototypeSettingsPinUnpinPanGestureTravelDistance;
+ (double)prototypeSettingsInteractiveAnimationSpringFriction;
+ (double)prototypeSettingsInteractiveAnimationSpringTension;
+ (double)prototypeSettingsAnimationSpringFriction;
+ (double)prototypeSettingsAnimationSpringTension;
+ (double)prototypeSettingsGestureRubberbandCoefficient;
+ (double)prototypeSettingsBlurFadeAnimationDuration;
+ (double)prototypeSettingsCornerRadius;
@property(readonly, nonatomic) long long layoutRole; // @synthesize layoutRole=_layoutRole;
@property(readonly, nonatomic) SBPanSystemGestureRecognizer *panSystemGestureRecognizer; // @synthesize panSystemGestureRecognizer=_panSystemGestureRecognizer;
@property(readonly, nonatomic) __weak SBMainDisplaySceneLayoutViewController *sceneLayoutViewController; // @synthesize sceneLayoutViewController=_sceneLayoutViewController;
- (void).cxx_destruct;
- (id)_floatingApplicationDeviceApplicationSceneViewController;
- (id)_floatingApplicationController;
- (long long)_backgroundLayoutRole;
- (long long)_foregroundLayoutRole;
- (id)_backgroundLayoutElementViewController;
- (id)_foregroundLayoutElementViewController;
- (void)_captureLayoutElementViewControllers;
- (void)_captureCompletionFloatingConfiguration;
- (void)_updateUserInterfaceAfterLayoutStateTransitionWithTransactionCompletion:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceBeforeLayoutStateTransitionWithTransactionCompletion:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceWithTranslation:(double)arg1 velocity:(double)arg2 systemGestureRecognizerBegan:(_Bool)arg3;
- (double)_valueFromSystemGestureRecognizerWithTranslation:(double)arg1 velocity:(double)arg2;
- (_Bool)_completeTransactionWithTranslation:(double)arg1 velocity:(double)arg2;
- (double)_systemGestureRecognizerVelocity;
- (double)_systemGestureRecognizerTranslation;
- (id)_layoutStateTransitionWorkspaceTransaction;
- (void)_systemGestureRecognizerFailed;
- (void)_systemGestureRecognizerEnded;
- (void)_systemGestureRecognizerChanged;
- (void)_systemGestureRecognizerBegan;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_didComplete;
- (void)_begin;
- (void)_finishWithCompletionType:(long long)arg1;
- (void)systemGestureStateChanged:(id)arg1;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 sceneLayoutViewController:(id)arg2 panSystemGestureRecognizer:(id)arg3 layoutRole:(long long)arg4;

@end

