//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@class NSString;

@interface UIColor (SBWallpaper)
+ (id)sb_colorWithRGBHexString:(id)arg1;
@property(readonly, copy, nonatomic) NSString *sb_RGBHexString;
@end

