//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIImage, UITraitCollection;

@protocol UIStatusBarCarPlayDockDataProviding <NSObject>
- (_Bool)shouldDisplayBadgeForBundleIdentifier:(NSString *)arg1;
- (NSString *)callDuration;
- (UIImage *)dockImageForBundleIdentifier:(NSString *)arg1 format:(int)arg2 traitCollection:(UITraitCollection *)arg3;
- (NSString *)activeBundleIdentifier;
- (NSArray *)bundleIdentifiers;
@end

