//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface UIWindow (SelfHosting)
- (id)sb_hostWrapperForUseInOrientation:(long long)arg1 hostRequester:(id)arg2 enable:(_Bool)arg3 orderFront:(_Bool)arg4;
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2 enable:(_Bool)arg3 orderFront:(_Bool)arg4;
- (id)sb_hostWrapperForUseInWindow:(id)arg1 hostRequester:(id)arg2;
@end

