//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollViewDelegate.h"

@class NSArray, UIScrollView, UIView, WGWidgetGroupViewController;

@protocol WGWidgetGroupViewControllerDelegate <UIScrollViewDelegate>

@optional
- (NSArray *)additionalBundleIdentifiersForAttribution:(WGWidgetGroupViewController *)arg1;
- (UIView *)widgetGroupViewController:(WGWidgetGroupViewController *)arg1 newCustomBackgroundViewForItem:(id)arg2 inScrollView:(UIScrollView *)arg3;
@end

